import xbmc

xbmc.executebuiltin("Action(reloadkeymaps)")
xbmc.executebuiltin("Action(VolumeUp)")
xbmc.executebuiltin("Action(VolumeUp)")
xbmc.executebuiltin("Action(VolumeUp)")
xbmc.executebuiltin("Action(VolumeUp)")
xbmc.executebuiltin("Action(VolumeUp)")
xbmc.executebuiltin("Action(VolumeUp)")
xbmc.executebuiltin("Action(VolumeUp)")
xbmc.executebuiltin("Action(VolumeUp)")
xbmc.executebuiltin("Action(VolumeUp)")
xbmc.executebuiltin("Action(VolumeUp)")
xbmc.executebuiltin("Action(VolumeUp)")
xbmc.executebuiltin("Action(VolumeUp)")
